### ISSUE TITLE
FIT of regiones to cluster centre

### ISSUE THREAD

**Issue by hannesfelipe** [nailend/ModITy#5]
When determining the type regions using ident_typregions, the FIT should also be output. This refers to the difference between the actual type region and the cluster centre. 

As a further option it would be great to have a table with all regions of the cluster and the least squared error. Then it would be possible to see how much worse ist the second, third ... best best region (or how good they also fit).

**Comment by hannesfelipe** [comment]
Short question about the new ident_typregions function. The return funtion puts the df_typregions and df_data into one dict. 
Wouldn't it be better to split it into two function?
On which return just the df_typregions (like the former function) and one fot the whole data? Like ident_typregions and ident_typregions_DataFIT?

**Comment by iuljan** [comment]
The return value of `ident_typregions()` is a tuple of two values.
It is common to use an underscore if the return value is of no interest
`typreregions, _ = ident_typregions(...)`
In my opinion, it is practical to return both with the same function as they depend on each other. Also you don't mix things up by having to choose the same keyword arguments for both functions.
Would you agree?

**Comment by iuljan** [comment]
I just removed some parantheses in the code, that might have had an effect on the return value
